// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.admin_user */
export type AdminUserId = number & { __brand: 'public.admin_user' };

/** Represents the table public.admin_user */
export default interface AdminUserTable {
  id: ColumnType<AdminUserId, AdminUserId | undefined, AdminUserId>;

  username: ColumnType<string, string, string>;

  password_hash: ColumnType<string, string, string>;

  created_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  first_name: ColumnType<string, string | undefined, string>;

  last_name: ColumnType<string, string | undefined, string>;

  phone_number: ColumnType<string | null, string | null, string | null>;
}

export type AdminUser = Selectable<AdminUserTable>;

export type NewAdminUser = Insertable<AdminUserTable>;

export type AdminUserUpdate = Updateable<AdminUserTable>;
