// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.client_view_record */
export type ClientViewRecordId = number & { __brand: 'public.client_view_record' };

/** Represents the table public.client_view_record */
export default interface ClientViewRecordTable {
  id: ColumnType<ClientViewRecordId, ClientViewRecordId | undefined, ClientViewRecordId>;

  user_id: ColumnType<number, number, number>;

  data: ColumnType<unknown, unknown, unknown>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type ClientViewRecord = Selectable<ClientViewRecordTable>;

export type NewClientViewRecord = Insertable<ClientViewRecordTable>;

export type ClientViewRecordUpdate = Updateable<ClientViewRecordTable>;
