// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { DefaultEmailVariableId } from './DefaultEmailVariable';
import type { CompanyId } from './Company';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.company_email_variable */
export type CompanyEmailVariableId = number & { __brand: 'public.company_email_variable' };

/** Represents the table public.company_email_variable */
export default interface CompanyEmailVariableTable {
  id: ColumnType<CompanyEmailVariableId, CompanyEmailVariableId | undefined, CompanyEmailVariableId>;

  default_email_variable_id: ColumnType<DefaultEmailVariableId, DefaultEmailVariableId, DefaultEmailVariableId>;

  company_id: ColumnType<CompanyId, CompanyId, CompanyId>;

  status: ColumnType<string, string | undefined, string>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type CompanyEmailVariable = Selectable<CompanyEmailVariableTable>;

export type NewCompanyEmailVariable = Insertable<CompanyEmailVariableTable>;

export type CompanyEmailVariableUpdate = Updateable<CompanyEmailVariableTable>;
