// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.company */
export type CompanyId = number & { __brand: 'public.company' };

/** Represents the table public.company */
export default interface CompanyTable {
  id: ColumnType<CompanyId, CompanyId | undefined, CompanyId>;

  name: ColumnType<string, string, string>;

  slug: ColumnType<string, string, string>;

  is_active: ColumnType<boolean, boolean | undefined, boolean>;

  connection_uri: ColumnType<string, string, string>;

  created_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  deleted_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  is_archived: ColumnType<boolean, boolean | undefined, boolean>;

  updated_at: ColumnType<Date | null, Date | string | null, Date | string | null>;
}

export type Company = Selectable<CompanyTable>;

export type NewCompany = Insertable<CompanyTable>;

export type CompanyUpdate = Updateable<CompanyTable>;
