// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { DefaultEmailTemplateId } from './DefaultEmailTemplate';
import type { CompanyId } from './Company';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.company_email_template */
export type CompanyEmailTemplateId = number & { __brand: 'public.company_email_template' };

/** Represents the table public.company_email_template */
export default interface CompanyEmailTemplateTable {
  id: ColumnType<CompanyEmailTemplateId, CompanyEmailTemplateId | undefined, CompanyEmailTemplateId>;

  default_email_template_id: ColumnType<DefaultEmailTemplateId, DefaultEmailTemplateId, DefaultEmailTemplateId>;

  company_id: ColumnType<CompanyId, CompanyId, CompanyId>;

  status: ColumnType<string, string | undefined, string>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type CompanyEmailTemplate = Selectable<CompanyEmailTemplateTable>;

export type NewCompanyEmailTemplate = Insertable<CompanyEmailTemplateTable>;

export type CompanyEmailTemplateUpdate = Updateable<CompanyEmailTemplateTable>;
