// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.country */
export type CountryId = number & { __brand: 'public.country' };

/** Represents the table public.country */
export default interface CountryTable {
  id: ColumnType<CountryId, CountryId | undefined, CountryId>;

  name: ColumnType<string, string, string>;

  code: ColumnType<string, string, string>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type Country = Selectable<CountryTable>;

export type NewCountry = Insertable<CountryTable>;

export type CountryUpdate = Updateable<CountryTable>;
