// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { CourseId } from './Course';
import type { CompanyId } from './Company';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Represents the table public.course_company */
export default interface CourseCompanyTable {
  course_id: ColumnType<CourseId, CourseId, CourseId>;

  company_id: ColumnType<CompanyId, CompanyId, CompanyId>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  number_of_seats: ColumnType<number | null, number | null, number | null>;
}

export type CourseCompany = Selectable<CourseCompanyTable>;

export type NewCourseCompany = Insertable<CourseCompanyTable>;

export type CourseCompanyUpdate = Updateable<CourseCompanyTable>;
