// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { CourseId } from './Course';
import type { ModuleId } from './Module';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.course_module */
export type CourseModuleId = number & { __brand: 'public.course_module' };

/** Represents the table public.course_module */
export default interface CourseModuleTable {
  id: ColumnType<CourseModuleId, CourseModuleId | undefined, CourseModuleId>;

  course_id: ColumnType<CourseId, CourseId, CourseId>;

  module_id: ColumnType<ModuleId, ModuleId, ModuleId>;

  created_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  updated_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  group_key: ColumnType<string, string, string>;

  days_to_complete: ColumnType<number | null, number | null, number | null>;
}

export type CourseModule = Selectable<CourseModuleTable>;

export type NewCourseModule = Insertable<CourseModuleTable>;

export type CourseModuleUpdate = Updateable<CourseModuleTable>;
