// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.course */
export type CourseId = number & { __brand: 'public.course' };

/** Represents the table public.course */
export default interface CourseTable {
  id: ColumnType<CourseId, CourseId | undefined, CourseId>;

  name: ColumnType<string, string, string>;

  created_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  updated_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  is_paid: ColumnType<boolean, boolean | undefined, boolean>;

  price: ColumnType<string | null, string | null, string | null>;

  deleted_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  description: ColumnType<string | null, string | null, string | null>;

  enrollment_validity_days: ColumnType<number | null, number | null, number | null>;

  completion_validity_days: ColumnType<number | null, number | null, number | null>;
}

export type Course = Selectable<CourseTable>;

export type NewCourse = Insertable<CourseTable>;

export type CourseUpdate = Updateable<CourseTable>;
