// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.default_apps */
export type DefaultAppsId = number & { __brand: 'public.default_apps' };

/** Represents the table public.default_apps */
export default interface DefaultAppsTable {
  id: ColumnType<DefaultAppsId, DefaultAppsId | undefined, DefaultAppsId>;

  order: ColumnType<number, number | undefined, number>;

  name: ColumnType<string, string, string>;

  key: ColumnType<string, string, string>;

  is_active: ColumnType<boolean, boolean | undefined, boolean>;

  total_seats: ColumnType<number, number | undefined, number>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type DefaultApps = Selectable<DefaultAppsTable>;

export type NewDefaultApps = Insertable<DefaultAppsTable>;

export type DefaultAppsUpdate = Updateable<DefaultAppsTable>;
