// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.default_email_template */
export type DefaultEmailTemplateId = number & { __brand: 'public.default_email_template' };

/** Represents the table public.default_email_template */
export default interface DefaultEmailTemplateTable {
  id: ColumnType<DefaultEmailTemplateId, DefaultEmailTemplateId | undefined, DefaultEmailTemplateId>;

  name: ColumnType<string, string, string>;

  description: ColumnType<string, string, string>;

  app_id: ColumnType<number, number, number>;

  email_type: ColumnType<string, string, string>;

  subject: ColumnType<string, string, string>;

  html_body: ColumnType<string, string, string>;

  plain_text_body: ColumnType<string, string, string>;

  is_active: ColumnType<boolean, boolean | undefined, boolean>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;

  deleted_at: ColumnType<Date | null, Date | string | null, Date | string | null>;
}

export type DefaultEmailTemplate = Selectable<DefaultEmailTemplateTable>;

export type NewDefaultEmailTemplate = Insertable<DefaultEmailTemplateTable>;

export type DefaultEmailTemplateUpdate = Updateable<DefaultEmailTemplateTable>;
