// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.default_email_variable */
export type DefaultEmailVariableId = number & { __brand: 'public.default_email_variable' };

/** Represents the table public.default_email_variable */
export default interface DefaultEmailVariableTable {
  id: ColumnType<DefaultEmailVariableId, DefaultEmailVariableId | undefined, DefaultEmailVariableId>;

  name: ColumnType<string, string, string>;

  value: ColumnType<string, string, string>;

  type: ColumnType<string, string | undefined, string>;

  field_identifier: ColumnType<string | null, string | null, string | null>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type DefaultEmailVariable = Selectable<DefaultEmailVariableTable>;

export type NewDefaultEmailVariable = Insertable<DefaultEmailVariableTable>;

export type DefaultEmailVariableUpdate = Updateable<DefaultEmailVariableTable>;
