// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { JobRoleId } from './JobRole';
import type { CourseId } from './Course';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.job_role_course */
export type JobRoleCourseId = number & { __brand: 'public.job_role_course' };

/** Represents the table public.job_role_course */
export default interface JobRoleCourseTable {
  id: ColumnType<JobRoleCourseId, JobRoleCourseId | undefined, JobRoleCourseId>;

  job_role_id: ColumnType<JobRoleId, JobRoleId, JobRoleId>;

  course_id: ColumnType<CourseId, CourseId, CourseId>;

  created_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  updated_at: ColumnType<Date | null, Date | string | null, Date | string | null>;
}

export type JobRoleCourse = Selectable<JobRoleCourseTable>;

export type NewJobRoleCourse = Insertable<JobRoleCourseTable>;

export type JobRoleCourseUpdate = Updateable<JobRoleCourseTable>;
