// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.job_role */
export type JobRoleId = number & { __brand: 'public.job_role' };

/** Represents the table public.job_role */
export default interface JobRoleTable {
  id: ColumnType<JobRoleId, JobRoleId | undefined, JobRoleId>;

  name: ColumnType<string, string, string>;

  description: ColumnType<string | null, string | null, string | null>;

  created_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  updated_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  status: ColumnType<string, string | undefined, string>;

  deleted_at: ColumnType<Date | null, Date | string | null, Date | string | null>;
}

export type JobRole = Selectable<JobRoleTable>;

export type NewJobRole = Insertable<JobRoleTable>;

export type JobRoleUpdate = Updateable<JobRoleTable>;
