// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { JobRoleId } from './JobRole';
import type { CompanyId } from './Company';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Represents the table public.job_role_company */
export default interface JobRoleCompanyTable {
  job_role_id: ColumnType<JobRoleId, JobRoleId, JobRoleId>;

  company_id: ColumnType<CompanyId, CompanyId, CompanyId>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  number_of_seats: ColumnType<number | null, number | null, number | null>;
}

export type JobRoleCompany = Selectable<JobRoleCompanyTable>;

export type NewJobRoleCompany = Insertable<JobRoleCompanyTable>;

export type JobRoleCompanyUpdate = Updateable<JobRoleCompanyTable>;
