// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { CompanyId } from './Company';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.login_activity */
export type LoginActivityId = number & { __brand: 'public.login_activity' };

/** Represents the table public.login_activity */
export default interface LoginActivityTable {
  id: ColumnType<LoginActivityId, LoginActivityId | undefined, LoginActivityId>;

  method: ColumnType<string, string, string>;

  location: ColumnType<string, string, string>;

  company_id: ColumnType<CompanyId, CompanyId, CompanyId>;

  user_info: ColumnType<unknown, unknown, unknown>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type LoginActivity = Selectable<LoginActivityTable>;

export type NewLoginActivity = Insertable<LoginActivityTable>;

export type LoginActivityUpdate = Updateable<LoginActivityTable>;
