// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.master_manual_form */
export type MasterManualFormId = number & { __brand: 'public.master_manual_form' };

/** Represents the table public.master_manual_form */
export default interface MasterManualFormTable {
  id: ColumnType<MasterManualFormId, MasterManualFormId | undefined, MasterManualFormId>;

  name: ColumnType<string, string, string>;

  file_url: ColumnType<string, string, string>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;

  access_type: ColumnType<string, string | undefined, string>;

  status: ColumnType<string, string | undefined, string>;
}

export type MasterManualForm = Selectable<MasterManualFormTable>;

export type NewMasterManualForm = Insertable<MasterManualFormTable>;

export type MasterManualFormUpdate = Updateable<MasterManualFormTable>;
