// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { MasterArticleId } from './MasterArticle';
import type { CompanyId } from './Company';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Represents the table public.master_article_company */
export default interface MasterArticleCompanyTable {
  master_article_id: ColumnType<MasterArticleId, MasterArticleId, MasterArticleId>;

  company_id: ColumnType<CompanyId, CompanyId, CompanyId>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  position: ColumnType<number, number | undefined, number>;

  archived_at: ColumnType<Date | null, Date | string | null, Date | string | null>;
}

export type MasterArticleCompany = Selectable<MasterArticleCompanyTable>;

export type NewMasterArticleCompany = Insertable<MasterArticleCompanyTable>;

export type MasterArticleCompanyUpdate = Updateable<MasterArticleCompanyTable>;
