// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { MasterCategoryId } from './MasterCategory';
import type { AdminUserId } from './AdminUser';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.master_article */
export type MasterArticleId = number & { __brand: 'public.master_article' };

/** Represents the table public.master_article */
export default interface MasterArticleTable {
  id: ColumnType<MasterArticleId, MasterArticleId | undefined, MasterArticleId>;

  name: ColumnType<string, string, string>;

  master_category_id: ColumnType<MasterCategoryId, MasterCategoryId, MasterCategoryId>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;

  upper_image_video_url: ColumnType<string | null, string | null, string | null>;

  lower_image_video_url: ColumnType<string | null, string | null, string | null>;

  is_reviewed: ColumnType<boolean, boolean | undefined, boolean>;

  review_date: ColumnType<Date | null, Date | string | null, Date | string | null>;

  reviewed_by_admin_id: ColumnType<AdminUserId | null, AdminUserId | null, AdminUserId | null>;

  deleted_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  is_approved: ColumnType<boolean, boolean | undefined, boolean>;

  review_status: ColumnType<string | null, string | null, string | null>;

  reviewer_comment: ColumnType<string | null, string | null, string | null>;

  review_completed_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  position: ColumnType<number, number | undefined, number>;
}

export type MasterArticle = Selectable<MasterArticleTable>;

export type NewMasterArticle = Insertable<MasterArticleTable>;

export type MasterArticleUpdate = Updateable<MasterArticleTable>;
