// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.master_category */
export type MasterCategoryId = number & { __brand: 'public.master_category' };

/** Represents the table public.master_category */
export default interface MasterCategoryTable {
  id: ColumnType<MasterCategoryId, MasterCategoryId | undefined, MasterCategoryId>;

  name: ColumnType<string, string, string>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;

  deleted_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  position: ColumnType<number, number | undefined, number>;
}

export type MasterCategory = Selectable<MasterCategoryTable>;

export type NewMasterCategory = Insertable<MasterCategoryTable>;

export type MasterCategoryUpdate = Updateable<MasterCategoryTable>;
