// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { MasterArticleId } from './MasterArticle';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.master_article_document */
export type MasterArticleDocumentId = number & { __brand: 'public.master_article_document' };

/** Represents the table public.master_article_document */
export default interface MasterArticleDocumentTable {
  id: ColumnType<MasterArticleDocumentId, MasterArticleDocumentId | undefined, MasterArticleDocumentId>;

  master_article_id: ColumnType<MasterArticleId, MasterArticleId, MasterArticleId>;

  name: ColumnType<string, string, string>;

  file_url: ColumnType<string, string, string>;

  order: ColumnType<number, number | undefined, number>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type MasterArticleDocument = Selectable<MasterArticleDocumentTable>;

export type NewMasterArticleDocument = Insertable<MasterArticleDocumentTable>;

export type MasterArticleDocumentUpdate = Updateable<MasterArticleDocumentTable>;
