// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { MasterArticleId } from './MasterArticle';
import type { MasterManualFormId } from './MasterManualForm';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Represents the table public.master_article_manual_form */
export default interface MasterArticleManualFormTable {
  master_article_id: ColumnType<MasterArticleId, MasterArticleId, MasterArticleId>;

  master_manual_form_id: ColumnType<MasterManualFormId, MasterManualFormId, MasterManualFormId>;

  is_public: ColumnType<boolean, boolean | undefined, boolean>;

  order: ColumnType<number, number | undefined, number>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type MasterArticleManualForm = Selectable<MasterArticleManualFormTable>;

export type NewMasterArticleManualForm = Insertable<MasterArticleManualFormTable>;

export type MasterArticleManualFormUpdate = Updateable<MasterArticleManualFormTable>;
