// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { MasterArticleId } from './MasterArticle';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.master_article_section */
export type MasterArticleSectionId = number & { __brand: 'public.master_article_section' };

/** Represents the table public.master_article_section */
export default interface MasterArticleSectionTable {
  id: ColumnType<MasterArticleSectionId, MasterArticleSectionId | undefined, MasterArticleSectionId>;

  master_article_id: ColumnType<MasterArticleId, MasterArticleId, MasterArticleId>;

  title: ColumnType<string, string, string>;

  description: ColumnType<string, string, string>;

  order: ColumnType<number, number | undefined, number>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type MasterArticleSection = Selectable<MasterArticleSectionTable>;

export type NewMasterArticleSection = Insertable<MasterArticleSectionTable>;

export type MasterArticleSectionUpdate = Updateable<MasterArticleSectionTable>;
