// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { MasterCategoryId } from './MasterCategory';
import type { CompanyId } from './Company';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.master_category_company_role */
export type MasterCategoryCompanyRoleRoleId = number & { __brand: 'public.master_category_company_role' };

/** Represents the table public.master_category_company_role */
export default interface MasterCategoryCompanyRoleTable {
  master_category_id: ColumnType<MasterCategoryId, MasterCategoryId, MasterCategoryId>;

  company_id: ColumnType<CompanyId, CompanyId, CompanyId>;

  role_id: ColumnType<MasterCategoryCompanyRoleRoleId, MasterCategoryCompanyRoleRoleId, MasterCategoryCompanyRoleRoleId>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type MasterCategoryCompanyRole = Selectable<MasterCategoryCompanyRoleTable>;

export type NewMasterCategoryCompanyRole = Insertable<MasterCategoryCompanyRoleTable>;

export type MasterCategoryCompanyRoleUpdate = Updateable<MasterCategoryCompanyRoleTable>;
