// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.master_article_history */
export type MasterArticleHistoryHistoryId = number & { __brand: 'public.master_article_history' };

/** Represents the table public.master_article_history */
export default interface MasterArticleHistoryTable {
  history_id: ColumnType<MasterArticleHistoryHistoryId, MasterArticleHistoryHistoryId | undefined, MasterArticleHistoryHistoryId>;

  version_timestamp: ColumnType<Date, Date | string | undefined, Date | string>;

  operation_type: ColumnType<string, string, string>;

  master_article_id: ColumnType<number, number, number>;

  name: ColumnType<string, string, string>;

  master_category_id: ColumnType<number | null, number | null, number | null>;

  upper_image_video_url: ColumnType<string | null, string | null, string | null>;

  lower_image_video_url: ColumnType<string | null, string | null, string | null>;

  is_reviewed: ColumnType<boolean | null, boolean | null, boolean | null>;

  review_date: ColumnType<Date | null, Date | string | null, Date | string | null>;

  is_approved: ColumnType<boolean | null, boolean | null, boolean | null>;

  review_status: ColumnType<string | null, string | null, string | null>;

  reviewer_comment: ColumnType<string | null, string | null, string | null>;

  review_completed_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  reviewed_by_admin_id: ColumnType<number | null, number | null, number | null>;

  relations_snapshot: ColumnType<unknown | null, unknown | null, unknown | null>;
}

export type MasterArticleHistory = Selectable<MasterArticleHistoryTable>;

export type NewMasterArticleHistory = Insertable<MasterArticleHistoryTable>;

export type MasterArticleHistoryUpdate = Updateable<MasterArticleHistoryTable>;
