// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { MasterCategoryId } from './MasterCategory';
import type { CompanyId } from './Company';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Represents the table public.master_category_company */
export default interface MasterCategoryCompanyTable {
  master_category_id: ColumnType<MasterCategoryId, MasterCategoryId, MasterCategoryId>;

  company_id: ColumnType<CompanyId, CompanyId, CompanyId>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  position: ColumnType<number, number | undefined, number>;

  archived_at: ColumnType<Date | null, Date | string | null, Date | string | null>;
}

export type MasterCategoryCompany = Selectable<MasterCategoryCompanyTable>;

export type NewMasterCategoryCompany = Insertable<MasterCategoryCompanyTable>;

export type MasterCategoryCompanyUpdate = Updateable<MasterCategoryCompanyTable>;
