// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { MasterArticleId } from './MasterArticle';
import type { MasterDigitalFormId } from './MasterDigitalForm';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Represents the table public.master_article_digital_form */
export default interface MasterArticleDigitalFormTable {
  master_article_id: ColumnType<MasterArticleId, MasterArticleId, MasterArticleId>;

  master_digital_form_id: ColumnType<MasterDigitalFormId, MasterDigitalFormId, MasterDigitalFormId>;

  order: ColumnType<number, number | undefined, number>;

  is_public: ColumnType<boolean, boolean | undefined, boolean>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type MasterArticleDigitalForm = Selectable<MasterArticleDigitalFormTable>;

export type NewMasterArticleDigitalForm = Insertable<MasterArticleDigitalFormTable>;

export type MasterArticleDigitalFormUpdate = Updateable<MasterArticleDigitalFormTable>;
