// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { MasterArticleId } from './MasterArticle';
import type { CompanyId } from './Company';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.master_article_company_role */
export type MasterArticleCompanyRoleRoleId = number & { __brand: 'public.master_article_company_role' };

/** Represents the table public.master_article_company_role */
export default interface MasterArticleCompanyRoleTable {
  master_article_id: ColumnType<MasterArticleId, MasterArticleId, MasterArticleId>;

  company_id: ColumnType<CompanyId, CompanyId, CompanyId>;

  role_id: ColumnType<MasterArticleCompanyRoleRoleId, MasterArticleCompanyRoleRoleId, MasterArticleCompanyRoleRoleId>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type MasterArticleCompanyRole = Selectable<MasterArticleCompanyRoleTable>;

export type NewMasterArticleCompanyRole = Insertable<MasterArticleCompanyRoleTable>;

export type MasterArticleCompanyRoleUpdate = Updateable<MasterArticleCompanyRoleTable>;
