// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.master_digital_form */
export type MasterDigitalFormId = number & { __brand: 'public.master_digital_form' };

/** Represents the table public.master_digital_form */
export default interface MasterDigitalFormTable {
  id: ColumnType<MasterDigitalFormId, MasterDigitalFormId | undefined, MasterDigitalFormId>;

  name: ColumnType<string, string, string>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;

  access_type: ColumnType<string, string | undefined, string>;

  status: ColumnType<string, string | undefined, string>;

  form_schema: ColumnType<unknown | null, unknown | null, unknown | null>;
}

export type MasterDigitalForm = Selectable<MasterDigitalFormTable>;

export type NewMasterDigitalForm = Insertable<MasterDigitalFormTable>;

export type MasterDigitalFormUpdate = Updateable<MasterDigitalFormTable>;
