// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { CompanyId } from './Company';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.message */
export type MessageId = number & { __brand: 'public.message' };

/** Represents the table public.message */
export default interface MessageTable {
  id: ColumnType<MessageId, MessageId | undefined, MessageId>;

  subject: ColumnType<string, string, string>;

  message: ColumnType<string, string, string>;

  company_id: ColumnType<CompanyId, CompanyId, CompanyId>;

  user_id: ColumnType<number, number, number>;

  parent_message_id: ColumnType<MessageId | null, MessageId | null, MessageId | null>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;

  deleted_at: ColumnType<Date | null, Date | string | null, Date | string | null>;
}

export type Message = Selectable<MessageTable>;

export type NewMessage = Insertable<MessageTable>;

export type MessageUpdate = Updateable<MessageTable>;
