// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ModuleId } from './Module';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.module_resource */
export type ModuleResourceId = number & { __brand: 'public.module_resource' };

/** Represents the table public.module_resource */
export default interface ModuleResourceTable {
  id: ColumnType<ModuleResourceId, ModuleResourceId | undefined, ModuleResourceId>;

  name: ColumnType<string, string, string>;

  path: ColumnType<string, string, string>;

  module_id: ColumnType<ModuleId | null, ModuleId | null, ModuleId | null>;

  user_id: ColumnType<number, number, number>;

  created_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  updated_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  type: ColumnType<string, string | undefined, string>;
}

export type ModuleResource = Selectable<ModuleResourceTable>;

export type NewModuleResource = Insertable<ModuleResourceTable>;

export type ModuleResourceUpdate = Updateable<ModuleResourceTable>;
