// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.module */
export type ModuleId = number & { __brand: 'public.module' };

/** Represents the table public.module */
export default interface ModuleTable {
  id: ColumnType<ModuleId, ModuleId | undefined, ModuleId>;

  name: ColumnType<string, string, string>;

  created_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  updated_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  type: ColumnType<string, string | undefined, string>;

  description: ColumnType<string | null, string | null, string | null>;

  is_active: ColumnType<boolean, boolean | undefined, boolean>;

  has_expiry: ColumnType<boolean | null, boolean | null, boolean | null>;
}

export type Module = Selectable<ModuleTable>;

export type NewModule = Insertable<ModuleTable>;

export type ModuleUpdate = Updateable<ModuleTable>;
