// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as ModuleTable } from './Module';
import type { default as MasterCategoryCompanyTable } from './MasterCategoryCompany';
import type { default as MasterCategoryCompanyRoleTable } from './MasterCategoryCompanyRole';
import type { default as ClientViewRecordTable } from './ClientViewRecord';
import type { default as MasterArticleSectionTable } from './MasterArticleSection';
import type { default as ReplicacheClientGroupTable } from './ReplicacheClientGroup';
import type { default as MessageTable } from './Message';
import type { default as DefaultAppsTable } from './DefaultApps';
import type { default as AdminUserTable } from './AdminUser';
import type { default as DefaultEmailTemplateTable } from './DefaultEmailTemplate';
import type { default as JobRoleTable } from './JobRole';
import type { default as MasterArticleHistoryTable } from './MasterArticleHistory';
import type { default as CompanyEmailVariableTable } from './CompanyEmailVariable';
import type { default as ReplicacheClientTable } from './ReplicacheClient';
import type { default as CourseCompanyTable } from './CourseCompany';
import type { default as MasterDigitalFormTable } from './MasterDigitalForm';
import type { default as CourseTable } from './Course';
import type { default as JobRoleCourseTable } from './JobRoleCourse';
import type { default as MasterArticleCompanyRoleTable } from './MasterArticleCompanyRole';
import type { default as SessionTable } from './Session';
import type { default as MasterCategoryTable } from './MasterCategory';
import type { default as DefaultEmailVariableTable } from './DefaultEmailVariable';
import type { default as LoginActivityTable } from './LoginActivity';
import type { default as MasterArticleManualFormTable } from './MasterArticleManualForm';
import type { default as MasterArticleDocumentTable } from './MasterArticleDocument';
import type { default as CompanyTable } from './Company';
import type { default as JobRoleCompanyTable } from './JobRoleCompany';
import type { default as MasterArticleTable } from './MasterArticle';
import type { default as ModuleResourceTable } from './ModuleResource';
import type { default as MasterArticleDigitalFormTable } from './MasterArticleDigitalForm';
import type { default as CountryTable } from './Country';
import type { default as CompanyEmailTemplateTable } from './CompanyEmailTemplate';
import type { default as MasterArticleCompanyTable } from './MasterArticleCompany';
import type { default as MasterManualFormTable } from './MasterManualForm';
import type { default as CourseModuleTable } from './CourseModule';

export default interface PublicSchema {
  module: ModuleTable;

  master_category_company: MasterCategoryCompanyTable;

  master_category_company_role: MasterCategoryCompanyRoleTable;

  client_view_record: ClientViewRecordTable;

  master_article_section: MasterArticleSectionTable;

  replicache_client_group: ReplicacheClientGroupTable;

  message: MessageTable;

  default_apps: DefaultAppsTable;

  admin_user: AdminUserTable;

  default_email_template: DefaultEmailTemplateTable;

  job_role: JobRoleTable;

  master_article_history: MasterArticleHistoryTable;

  company_email_variable: CompanyEmailVariableTable;

  replicache_client: ReplicacheClientTable;

  course_company: CourseCompanyTable;

  master_digital_form: MasterDigitalFormTable;

  course: CourseTable;

  job_role_course: JobRoleCourseTable;

  master_article_company_role: MasterArticleCompanyRoleTable;

  session: SessionTable;

  master_category: MasterCategoryTable;

  default_email_variable: DefaultEmailVariableTable;

  login_activity: LoginActivityTable;

  master_article_manual_form: MasterArticleManualFormTable;

  master_article_document: MasterArticleDocumentTable;

  company: CompanyTable;

  job_role_company: JobRoleCompanyTable;

  master_article: MasterArticleTable;

  module_resource: ModuleResourceTable;

  master_article_digital_form: MasterArticleDigitalFormTable;

  country: CountryTable;

  company_email_template: CompanyEmailTemplateTable;

  master_article_company: MasterArticleCompanyTable;

  master_manual_form: MasterManualFormTable;

  course_module: CourseModuleTable;
}
