// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.session */
export type SessionId = string & { __brand: 'public.session' };

/** Represents the table public.session */
export default interface SessionTable {
  id: ColumnType<SessionId, SessionId, SessionId>;

  user_id: ColumnType<number, number, number>;

  expires_at: ColumnType<number, number, number>;
}

export type Session = Selectable<SessionTable>;

export type NewSession = Insertable<SessionTable>;

export type SessionUpdate = Updateable<SessionTable>;
