// lib/mock-data.ts

import type { CourseWithDetails } from '@/types/courses';

const LONG_COMPANY_STRING = "ISO Safety, ASHR Construction, Mond Corp., Safety Culture, ABC Solutions, Richmond Tech, YSP Corp., iAuditor";

export const MOCK_COURSES: CourseWithDetails[] = [
  {
    id: 151,
    name: "Project Management Workshop",
    is_paid: false,
    price: null,
    totalUnits: 2,
    companyCount: 4,
    assignedCompanies: LONG_COMPANY_STRING,
    updatedAt: new Date('2023-10-15T10:00:00Z'),
    description: "Learn the fundamentals of project management.",
    enrollmentValidityDays: 365,
    completionValidityDays: null,
  },
  {
    id: 152,
    name: "Leadership Development Program",
    is_paid: false,
    price: null,
    totalUnits: 3,
    companyCount: 4,
    assignedCompanies: LONG_COMPANY_STRING,
    updatedAt: new Date('2023-11-20T14:30:00Z'),
    description: "Develop essential leadership skills.",
    enrollmentValidityDays: null,
    completionValidityDays: 365,
  },
  {
    id: 153,
    name: "Data Analytics Bootcamp",
    is_paid: false,
    price: null,
    totalUnits: 4,
    companyCount: 4,
    assignedCompanies: LONG_COMPANY_STRING,
    updatedAt: new Date('2024-01-05T09:15:00Z'),
    description: "Intensive course on data analysis tools.",
    enrollmentValidityDays: 180,
    completionValidityDays: null,
  },
  {
    id: 154,
    name: "Project Management Essentials",
    is_paid: false,
    price: null,
    totalUnits: 5,
    companyCount: 4,
    assignedCompanies: LONG_COMPANY_STRING,
    updatedAt: new Date('2024-01-10T11:00:00Z'),
    description: "Core concepts for managing projects effectively.",
    enrollmentValidityDays: null,
    completionValidityDays: null,
  },
  {
    id: 155,
    name: "Effective Communication Skills",
    is_paid: false,
    price: null,
    totalUnits: 2,
    companyCount: 4,
    assignedCompanies: LONG_COMPANY_STRING,
    updatedAt: new Date('2024-02-01T13:45:00Z'),
    description: "Improve your verbal and written communication.",
    enrollmentValidityDays: 365,
    completionValidityDays: 730,
  },
  {
    id: 156,
    name: "Time Management Techniques",
    is_paid: false,
    price: null,
    totalUnits: 1,
    companyCount: 4,
    assignedCompanies: LONG_COMPANY_STRING,
    updatedAt: new Date('2024-02-15T08:30:00Z'),
    description: "Master your schedule and increase productivity.",
    enrollmentValidityDays: null,
    completionValidityDays: null,
  },
  {
    id: 157,
    name: "Team Building Activities",
    is_paid: false,
    price: null,
    totalUnits: 6,
    companyCount: 4,
    assignedCompanies: LONG_COMPANY_STRING,
    updatedAt: new Date('2024-03-01T15:20:00Z'),
    description: "Strategies for building cohesive teams.",
    enrollmentValidityDays: 90,
    completionValidityDays: null,
  },
  {
    id: 158,
    name: "Customer Service Excellence",
    is_paid: false,
    price: null,
    totalUnits: 2,
    companyCount: 4,
    assignedCompanies: LONG_COMPANY_STRING,
    updatedAt: new Date('2024-03-10T10:10:00Z'),
    description: "Delivering outstanding customer experiences.",
    enrollmentValidityDays: 365,
    completionValidityDays: 365,
  },
  {
    id: 159,
    name: "Conflict Resolution Strategies",
    is_paid: false,
    price: null,
    totalUnits: 3,
    companyCount: 4,
    assignedCompanies: LONG_COMPANY_STRING,
    updatedAt: new Date('2024-03-20T16:00:00Z'),
    description: "Methods for resolving workplace conflicts.",
    enrollmentValidityDays: null,
    completionValidityDays: null,
  },
  {
    id: 160,
    name: "Sales Fundamentals Training",
    is_paid: false,
    price: null,
    totalUnits: 7,
    companyCount: 4,
    assignedCompanies: LONG_COMPANY_STRING,
    updatedAt: new Date('2024-04-05T09:00:00Z'),
    description: "Basic principles of successful selling.",
    enrollmentValidityDays: 180,
    completionValidityDays: 365,
  }
];
