// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.app */
export type AppId = number & { __brand: 'public.app' };

/** Represents the Kysely type for the app table. */
export default interface AppTable {
  id: ColumnType<AppId, AppId | undefined, AppId>;

  order: ColumnType<number, number | undefined, number>;

  name: ColumnType<string, string, string>;

  key: ColumnType<string, string, string>;

  is_active: ColumnType<boolean, boolean | undefined, boolean>;

  total_seats: ColumnType<number, number | undefined, number>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type App = Selectable<AppTable>;

export type NewApp = Insertable<AppTable>;

export type AppUpdate = Updateable<AppTable>;
