// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AppId } from './App';
import type { UserId } from './User';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.app_seat_allocation */
export type AppSeatAllocationId = number & { __brand: 'public.app_seat_allocation' };

/** Represents the Kysely type for the app_seat_allocation table. */
export default interface AppSeatAllocationTable {
  id: ColumnType<AppSeatAllocationId, AppSeatAllocationId | undefined, AppSeatAllocationId>;

  app_id: ColumnType<AppId, AppId, AppId>;

  user_id: ColumnType<UserId, UserId, UserId>;

  allocated_at: ColumnType<Date, Date | string | undefined, Date | string>;

  released_at: ColumnType<Date | null, Date | string | null, Date | string | null>;
}

export type AppSeatAllocation = Selectable<AppSeatAllocationTable>;

export type NewAppSeatAllocation = Insertable<AppSeatAllocationTable>;

export type AppSeatAllocationUpdate = Updateable<AppSeatAllocationTable>;
