// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.branding */
export type BrandingId = string & { __brand: 'public.branding' };

/** Represents the Kysely type for the branding table. */
export default interface BrandingTable {
  id: ColumnType<BrandingId, BrandingId | undefined, BrandingId>;

  name: ColumnType<string, string, string>;

  type: ColumnType<string, string, string>;

  value: ColumnType<string, string, string>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type Branding = Selectable<BrandingTable>;

export type NewBranding = Insertable<BrandingTable>;

export type BrandingUpdate = Updateable<BrandingTable>;
