// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.company_country */
export type CompanyCountryId = number & { __brand: 'public.company_country' };

/** Represents the Kysely type for the company_country table. */
export default interface CompanyCountryTable {
  id: ColumnType<CompanyCountryId, CompanyCountryId | undefined, CompanyCountryId>;

  country_id: ColumnType<number, number, number>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type CompanyCountry = Selectable<CompanyCountryTable>;

export type NewCompanyCountry = Insertable<CompanyCountryTable>;

export type CompanyCountryUpdate = Updateable<CompanyCountryTable>;
