// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.company_detail */
export type CompanyDetailId = string & { __brand: 'public.company_detail' };

/** Represents the Kysely type for the company_detail table. */
export default interface CompanyDetailTable {
  id: ColumnType<CompanyDetailId, CompanyDetailId | undefined, CompanyDetailId>;

  name: ColumnType<string, string | undefined, string>;

  slug: ColumnType<string, string | undefined, string>;

  phone_number: ColumnType<number | null, number | null, number | null>;

  is_active: ColumnType<boolean, boolean | undefined, boolean>;

  image_url: ColumnType<string, string | undefined, string>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type CompanyDetail = Selectable<CompanyDetailTable>;

export type NewCompanyDetail = Insertable<CompanyDetailTable>;

export type CompanyDetailUpdate = Updateable<CompanyDetailTable>;
