// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AppId } from './App';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.email_template */
export type EmailTemplateId = number & { __brand: 'public.email_template' };

/** Represents the Kysely type for the email_template table. */
export default interface EmailTemplateTable {
  id: ColumnType<EmailTemplateId, EmailTemplateId | undefined, EmailTemplateId>;

  name: ColumnType<string, string, string>;

  description: ColumnType<string, string, string>;

  app_id: ColumnType<AppId, AppId, AppId>;

  email_type: ColumnType<string, string, string>;

  subject: ColumnType<string, string, string>;

  html_body: ColumnType<string, string, string>;

  plain_text_body: ColumnType<string, string, string>;

  is_active: ColumnType<boolean, boolean | undefined, boolean>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;

  deleted_at: ColumnType<Date | null, Date | string | null, Date | string | null>;
}

export type EmailTemplate = Selectable<EmailTemplateTable>;

export type NewEmailTemplate = Insertable<EmailTemplateTable>;

export type EmailTemplateUpdate = Updateable<EmailTemplateTable>;
