// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.email_variable */
export type EmailVariableId = number & { __brand: 'public.email_variable' };

/** Represents the Kysely type for the email_variable table. */
export default interface EmailVariableTable {
  id: ColumnType<EmailVariableId, EmailVariableId | undefined, EmailVariableId>;

  name: ColumnType<string, string, string>;

  value: ColumnType<string, string, string>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;

  type: ColumnType<string, string | undefined, string>;

  field_identifier: ColumnType<string | null, string | null, string | null>;
}

export type EmailVariable = Selectable<EmailVariableTable>;

export type NewEmailVariable = Insertable<EmailVariableTable>;

export type EmailVariableUpdate = Updateable<EmailVariableTable>;
