// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UserId } from './User';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.email_verification_request */
export type EmailVerificationRequestId = string & { __brand: 'public.email_verification_request' };

/** Represents the Kysely type for the email_verification_request table. */
export default interface EmailVerificationRequestTable {
  id: ColumnType<EmailVerificationRequestId, EmailVerificationRequestId, EmailVerificationRequestId>;

  user_id: ColumnType<UserId, UserId, UserId>;

  email: ColumnType<string, string, string>;

  code: ColumnType<string, string, string>;

  expires_at: ColumnType<number, number, number>;
}

export type EmailVerificationRequest = Selectable<EmailVerificationRequestTable>;

export type NewEmailVerificationRequest = Insertable<EmailVerificationRequestTable>;

export type EmailVerificationRequestUpdate = Updateable<EmailVerificationRequestTable>;
