// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UserId } from './User';
import type { LocalDigitalFormId } from './LocalDigitalForm';
import type { SiteId } from './Site';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.form_submission */
export type FormSubmissionId = number & { __brand: 'public.form_submission' };

/** Represents the Kysely type for the form_submission table. */
export default interface FormSubmissionTable {
  id: ColumnType<FormSubmissionId, FormSubmissionId | undefined, FormSubmissionId>;

  master_digital_form_id: ColumnType<number | null, number | null, number | null>;

  submitted_by_user_id: ColumnType<UserId | null, UserId | null, UserId | null>;

  submission_data: ColumnType<unknown, unknown, unknown>;

  submitted_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  local_digital_form_id: ColumnType<LocalDigitalFormId | null, LocalDigitalFormId | null, LocalDigitalFormId | null>;

  site_id: ColumnType<SiteId | null, SiteId | null, SiteId | null>;

  status: ColumnType<string | null, string | null, string | null>;

  guest_full_name: ColumnType<string | null, string | null, string | null>;

  guest_phone_number: ColumnType<string | null, string | null, string | null>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;

  archived_at: ColumnType<Date | null, Date | string | null, Date | string | null>;
}

export type FormSubmission = Selectable<FormSubmissionTable>;

export type NewFormSubmission = Insertable<FormSubmissionTable>;

export type FormSubmissionUpdate = Updateable<FormSubmissionTable>;
