// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.local_digital_form */
export type LocalDigitalFormId = number & { __brand: 'public.local_digital_form' };

/** Represents the Kysely type for the local_digital_form table. */
export default interface LocalDigitalFormTable {
  id: ColumnType<LocalDigitalFormId, LocalDigitalFormId | undefined, LocalDigitalFormId>;

  name: ColumnType<string, string, string>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;

  form_schema: ColumnType<unknown | null, unknown | null, unknown | null>;

  status: ColumnType<string, string | undefined, string>;

  master_digital_form_id: ColumnType<number | null, number | null, number | null>;
}

export type LocalDigitalForm = Selectable<LocalDigitalFormTable>;

export type NewLocalDigitalForm = Insertable<LocalDigitalFormTable>;

export type LocalDigitalFormUpdate = Updateable<LocalDigitalFormTable>;
