// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { LocalCategoryId } from './LocalCategory';
import type { UserId } from './User';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.local_article */
export type LocalArticleId = number & { __brand: 'public.local_article' };

/** Represents the Kysely type for the local_article table. */
export default interface LocalArticleTable {
  id: ColumnType<LocalArticleId, LocalArticleId | undefined, LocalArticleId>;

  name: ColumnType<string, string, string>;

  local_category_id: ColumnType<LocalCategoryId | null, LocalCategoryId | null, LocalCategoryId | null>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;

  deleted_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  master_category_id: ColumnType<number | null, number | null, number | null>;

  upper_image_video_url: ColumnType<string | null, string | null, string | null>;

  lower_image_video_url: ColumnType<string | null, string | null, string | null>;

  is_reviewed: ColumnType<boolean, boolean | undefined, boolean>;

  review_date: ColumnType<Date | null, Date | string | null, Date | string | null>;

  reviewed_by_admin_id: ColumnType<UserId | null, UserId | null, UserId | null>;

  is_approved: ColumnType<boolean, boolean | undefined, boolean>;

  review_status: ColumnType<string | null, string | null, string | null>;

  reviewer_comment: ColumnType<string | null, string | null, string | null>;

  review_completed_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  original_master_article_id: ColumnType<number | null, number | null, number | null>;

  position: ColumnType<number, number | undefined, number>;
}

export type LocalArticle = Selectable<LocalArticleTable>;

export type NewLocalArticle = Insertable<LocalArticleTable>;

export type LocalArticleUpdate = Updateable<LocalArticleTable>;
