// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { LocalArticleId } from './LocalArticle';
import type { SiteId } from './Site';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Represents the Kysely type for the local_article_site table. */
export default interface LocalArticleSiteTable {
  local_article_id: ColumnType<LocalArticleId, LocalArticleId, LocalArticleId>;

  site_id: ColumnType<SiteId, SiteId, SiteId>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type LocalArticleSite = Selectable<LocalArticleSiteTable>;

export type NewLocalArticleSite = Insertable<LocalArticleSiteTable>;

export type LocalArticleSiteUpdate = Updateable<LocalArticleSiteTable>;
