// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { SiteId } from './Site';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.local_category */
export type LocalCategoryId = number & { __brand: 'public.local_category' };

/** Represents the Kysely type for the local_category table. */
export default interface LocalCategoryTable {
  id: ColumnType<LocalCategoryId, LocalCategoryId | undefined, LocalCategoryId>;

  name: ColumnType<string, string, string>;

  position: ColumnType<number, number | undefined, number>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;

  deleted_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  site_id: ColumnType<SiteId | null, SiteId | null, SiteId | null>;
}

export type LocalCategory = Selectable<LocalCategoryTable>;

export type NewLocalCategory = Insertable<LocalCategoryTable>;

export type LocalCategoryUpdate = Updateable<LocalCategoryTable>;
