// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { LocalArticleId } from './LocalArticle';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.local_article_document */
export type LocalArticleDocumentId = number & { __brand: 'public.local_article_document' };

/** Represents the Kysely type for the local_article_document table. */
export default interface LocalArticleDocumentTable {
  id: ColumnType<LocalArticleDocumentId, LocalArticleDocumentId | undefined, LocalArticleDocumentId>;

  local_article_id: ColumnType<LocalArticleId, LocalArticleId, LocalArticleId>;

  name: ColumnType<string, string, string>;

  file_url: ColumnType<string, string, string>;

  order: ColumnType<number, number | undefined, number>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type LocalArticleDocument = Selectable<LocalArticleDocumentTable>;

export type NewLocalArticleDocument = Insertable<LocalArticleDocumentTable>;

export type LocalArticleDocumentUpdate = Updateable<LocalArticleDocumentTable>;
