// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { LocalArticleId } from './LocalArticle';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.local_article_section */
export type LocalArticleSectionId = number & { __brand: 'public.local_article_section' };

/** Represents the Kysely type for the local_article_section table. */
export default interface LocalArticleSectionTable {
  id: ColumnType<LocalArticleSectionId, LocalArticleSectionId | undefined, LocalArticleSectionId>;

  local_article_id: ColumnType<LocalArticleId, LocalArticleId, LocalArticleId>;

  title: ColumnType<string, string, string>;

  description: ColumnType<string, string, string>;

  order: ColumnType<number, number | undefined, number>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type LocalArticleSection = Selectable<LocalArticleSectionTable>;

export type NewLocalArticleSection = Insertable<LocalArticleSectionTable>;

export type LocalArticleSectionUpdate = Updateable<LocalArticleSectionTable>;
