// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.local_article_history */
export type LocalArticleHistoryHistoryId = number & { __brand: 'public.local_article_history' };

/** Represents the Kysely type for the local_article_history table. */
export default interface LocalArticleHistoryTable {
  history_id: ColumnType<LocalArticleHistoryHistoryId, LocalArticleHistoryHistoryId | undefined, LocalArticleHistoryHistoryId>;

  version_timestamp: ColumnType<Date, Date | string | undefined, Date | string>;

  operation_type: ColumnType<string, string, string>;

  local_article_id: ColumnType<number, number, number>;

  name: ColumnType<string, string, string>;

  local_category_id: ColumnType<number | null, number | null, number | null>;

  master_category_id: ColumnType<number | null, number | null, number | null>;

  upper_image_video_url: ColumnType<string | null, string | null, string | null>;

  lower_image_video_url: ColumnType<string | null, string | null, string | null>;

  is_approved: ColumnType<boolean | null, boolean | null, boolean | null>;

  review_status: ColumnType<string | null, string | null, string | null>;

  reviewer_comment: ColumnType<string | null, string | null, string | null>;

  review_due_date: ColumnType<Date | null, Date | string | null, Date | string | null>;

  review_completed_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  reviewed_by_admin_id: ColumnType<number | null, number | null, number | null>;

  relations_snapshot: ColumnType<unknown | null, unknown | null, unknown | null>;

  is_reviewed: ColumnType<boolean | null, boolean | null, boolean | null>;
}

export type LocalArticleHistory = Selectable<LocalArticleHistoryTable>;

export type NewLocalArticleHistory = Insertable<LocalArticleHistoryTable>;

export type LocalArticleHistoryUpdate = Updateable<LocalArticleHistoryTable>;
