// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.location */
export type LocationId = number & { __brand: 'public.location' };

/** Represents the Kysely type for the location table. */
export default interface LocationTable {
  id: ColumnType<LocationId, LocationId | undefined, LocationId>;

  name: ColumnType<string, string, string>;

  location_type: ColumnType<string, string, string>;

  country_id: ColumnType<number, number, number>;

  parent_location_id: ColumnType<LocationId | null, LocationId | null, LocationId | null>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type Location = Selectable<LocationTable>;

export type NewLocation = Insertable<LocationTable>;

export type LocationUpdate = Updateable<LocationTable>;
