// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { LocalArticleId } from './LocalArticle';
import type { LocalDigitalFormId } from './LocalDigitalForm';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Represents the Kysely type for the local_article_digital_form table. */
export default interface LocalArticleDigitalFormTable {
  local_article_id: ColumnType<LocalArticleId, LocalArticleId, LocalArticleId>;

  local_digital_form_id: ColumnType<LocalDigitalFormId, LocalDigitalFormId, LocalDigitalFormId>;

  order: ColumnType<number, number | undefined, number>;

  is_public: ColumnType<boolean, boolean | undefined, boolean>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type LocalArticleDigitalForm = Selectable<LocalArticleDigitalFormTable>;

export type NewLocalArticleDigitalForm = Insertable<LocalArticleDigitalFormTable>;

export type LocalArticleDigitalFormUpdate = Updateable<LocalArticleDigitalFormTable>;
