// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.local_manual_form */
export type LocalManualFormId = number & { __brand: 'public.local_manual_form' };

/** Represents the Kysely type for the local_manual_form table. */
export default interface LocalManualFormTable {
  id: ColumnType<LocalManualFormId, LocalManualFormId | undefined, LocalManualFormId>;

  name: ColumnType<string, string, string>;

  file_url: ColumnType<string, string, string>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type LocalManualForm = Selectable<LocalManualFormTable>;

export type NewLocalManualForm = Insertable<LocalManualFormTable>;

export type LocalManualFormUpdate = Updateable<LocalManualFormTable>;
