// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { LocalArticleId } from './LocalArticle';
import type { LocalManualFormId } from './LocalManualForm';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Represents the Kysely type for the local_article_manual_form table. */
export default interface LocalArticleManualFormTable {
  local_article_id: ColumnType<LocalArticleId, LocalArticleId, LocalArticleId>;

  local_manual_form_id: ColumnType<LocalManualFormId, LocalManualFormId, LocalManualFormId>;

  is_public: ColumnType<boolean, boolean | undefined, boolean>;

  order: ColumnType<number, number | undefined, number>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type LocalArticleManualForm = Selectable<LocalArticleManualFormTable>;

export type NewLocalArticleManualForm = Insertable<LocalArticleManualFormTable>;

export type LocalArticleManualFormUpdate = Updateable<LocalArticleManualFormTable>;
