// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { LocalCategoryId } from './LocalCategory';
import type { RoleId } from './Role';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Represents the Kysely type for the local_category_role table. */
export default interface LocalCategoryRoleTable {
  local_category_id: ColumnType<LocalCategoryId, LocalCategoryId, LocalCategoryId>;

  role_id: ColumnType<RoleId, RoleId, RoleId>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type LocalCategoryRole = Selectable<LocalCategoryRoleTable>;

export type NewLocalCategoryRole = Insertable<LocalCategoryRoleTable>;

export type LocalCategoryRoleUpdate = Updateable<LocalCategoryRoleTable>;
