// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { LocalArticleId } from './LocalArticle';
import type { RoleId } from './Role';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Represents the Kysely type for the local_article_role table. */
export default interface LocalArticleRoleTable {
  local_article_id: ColumnType<LocalArticleId, LocalArticleId, LocalArticleId>;

  role_id: ColumnType<RoleId, RoleId, RoleId>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type LocalArticleRole = Selectable<LocalArticleRoleTable>;

export type NewLocalArticleRole = Insertable<LocalArticleRoleTable>;

export type LocalArticleRoleUpdate = Updateable<LocalArticleRoleTable>;
