// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UserId } from './User';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.login_activity */
export type LoginActivityId = number & { __brand: 'public.login_activity' };

/** Represents the Kysely type for the login_activity table. */
export default interface LoginActivityTable {
  id: ColumnType<LoginActivityId, LoginActivityId | undefined, LoginActivityId>;

  user_id: ColumnType<UserId, UserId, UserId>;

  data: ColumnType<unknown, unknown, unknown>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type LoginActivity = Selectable<LoginActivityTable>;

export type NewLoginActivity = Insertable<LoginActivityTable>;

export type LoginActivityUpdate = Updateable<LoginActivityTable>;
