// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UserId } from './User';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.password_reset_session */
export type PasswordResetSessionId = string & { __brand: 'public.password_reset_session' };

/** Represents the Kysely type for the password_reset_session table. */
export default interface PasswordResetSessionTable {
  id: ColumnType<PasswordResetSessionId, PasswordResetSessionId, PasswordResetSessionId>;

  user_id: ColumnType<UserId, UserId, UserId>;

  email: ColumnType<string, string, string>;

  code: ColumnType<string, string, string>;

  expires_at: ColumnType<number, number, number>;

  email_verified: ColumnType<boolean, boolean | undefined, boolean>;

  two_factor_verified: ColumnType<boolean, boolean | undefined, boolean>;
}

export type PasswordResetSession = Selectable<PasswordResetSessionTable>;

export type NewPasswordResetSession = Insertable<PasswordResetSessionTable>;

export type PasswordResetSessionUpdate = Updateable<PasswordResetSessionTable>;
