// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.permission */
export type PermissionId = number & { __brand: 'public.permission' };

/** Represents the Kysely type for the permission table. */
export default interface PermissionTable {
  id: ColumnType<PermissionId, PermissionId | undefined, PermissionId>;

  permission: ColumnType<string, string, string>;
}

export type Permission = Selectable<PermissionTable>;

export type NewPermission = Insertable<PermissionTable>;

export type PermissionUpdate = Updateable<PermissionTable>;
