// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as AppSeatAllocationTable } from './AppSeatAllocation';
import type { default as LocalArticleSiteTable } from './LocalArticleSite';
import type { default as UserModuleVerificationTable } from './UserModuleVerification';
import type { default as RolePermissionTable } from './RolePermission';
import type { default as VerificationSessionTable } from './VerificationSession';
import type { default as EmailVerificationRequestTable } from './EmailVerificationRequest';
import type { default as LocalArticleRoleTable } from './LocalArticleRole';
import type { default as LoginActivityTable } from './LoginActivity';
import type { default as UserModuleSubmissionTable } from './UserModuleSubmission';
import type { default as EmailVariableTable } from './EmailVariable';
import type { default as BrandingTable } from './Branding';
import type { default as LocalArticleTable } from './LocalArticle';
import type { default as EmailTemplateTable } from './EmailTemplate';
import type { default as LocalArticleDigitalFormTable } from './LocalArticleDigitalForm';
import type { default as LocalManualFormTable } from './LocalManualForm';
import type { default as LocalArticleDocumentTable } from './LocalArticleDocument';
import type { default as LocalDigitalFormTable } from './LocalDigitalForm';
import type { default as UserJobRoleTable } from './UserJobRole';
import type { default as UserCategoryTable } from './UserCategory';
import type { default as UserSiteRoleTable } from './UserSiteRole';
import type { default as LocalCategoryRoleTable } from './LocalCategoryRole';
import type { default as PermissionTable } from './Permission';
import type { default as AppTable } from './App';
import type { default as LocationTable } from './Location';
import type { default as LocalArticleManualFormTable } from './LocalArticleManualForm';
import type { default as SessionTable } from './Session';
import type { default as PasswordResetSessionTable } from './PasswordResetSession';
import type { default as UserCourseTable } from './UserCourse';
import type { default as LocalArticleHistoryTable } from './LocalArticleHistory';
import type { default as CompanyDetailTable } from './CompanyDetail';
import type { default as SiteTable } from './Site';
import type { default as FormSubmissionTable } from './FormSubmission';
import type { default as UserTable } from './User';
import type { default as LocalCategoryTable } from './LocalCategory';
import type { default as CompanyCountryTable } from './CompanyCountry';
import type { default as LocalArticleSectionTable } from './LocalArticleSection';
import type { default as UserScormAttemptTable } from './UserScormAttempt';
import type { default as RoleTable } from './Role';

export default interface PublicSchema {
  app_seat_allocation: AppSeatAllocationTable;

  local_article_site: LocalArticleSiteTable;

  user_module_verification: UserModuleVerificationTable;

  role_permission: RolePermissionTable;

  verification_session: VerificationSessionTable;

  email_verification_request: EmailVerificationRequestTable;

  local_article_role: LocalArticleRoleTable;

  login_activity: LoginActivityTable;

  user_module_submission: UserModuleSubmissionTable;

  email_variable: EmailVariableTable;

  branding: BrandingTable;

  local_article: LocalArticleTable;

  email_template: EmailTemplateTable;

  local_article_digital_form: LocalArticleDigitalFormTable;

  local_manual_form: LocalManualFormTable;

  local_article_document: LocalArticleDocumentTable;

  local_digital_form: LocalDigitalFormTable;

  user_job_role: UserJobRoleTable;

  user_category: UserCategoryTable;

  user_site_role: UserSiteRoleTable;

  local_category_role: LocalCategoryRoleTable;

  permission: PermissionTable;

  app: AppTable;

  location: LocationTable;

  local_article_manual_form: LocalArticleManualFormTable;

  session: SessionTable;

  password_reset_session: PasswordResetSessionTable;

  user_course: UserCourseTable;

  local_article_history: LocalArticleHistoryTable;

  company_detail: CompanyDetailTable;

  site: SiteTable;

  form_submission: FormSubmissionTable;

  user: UserTable;

  local_category: LocalCategoryTable;

  company_country: CompanyCountryTable;

  local_article_section: LocalArticleSectionTable;

  user_scorm_attempt: UserScormAttemptTable;

  role: RoleTable;
}
