// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { RoleId } from './Role';
import type { PermissionId } from './Permission';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Represents the Kysely type for the role_permission table. */
export default interface RolePermissionTable {
  role_id: ColumnType<RoleId, RoleId, RoleId>;

  permission_id: ColumnType<PermissionId, PermissionId, PermissionId>;
}

export type RolePermission = Selectable<RolePermissionTable>;

export type NewRolePermission = Insertable<RolePermissionTable>;

export type RolePermissionUpdate = Updateable<RolePermissionTable>;
