// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.role */
export type RoleId = number & { __brand: 'public.role' };

/** Represents the Kysely type for the role table. */
export default interface RoleTable {
  id: ColumnType<RoleId, RoleId | undefined, RoleId>;

  slug: ColumnType<string, string, string>;

  display_name: ColumnType<string, string, string>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;

  deleted_at: ColumnType<Date | null, Date | string | null, Date | string | null>;
}

export type Role = Selectable<RoleTable>;

export type NewRole = Insertable<RoleTable>;

export type RoleUpdate = Updateable<RoleTable>;
