// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UserId } from './User';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.session */
export type SessionId = string & { __brand: 'public.session' };

/** Represents the Kysely type for the session table. */
export default interface SessionTable {
  id: ColumnType<SessionId, SessionId, SessionId>;

  user_id: ColumnType<UserId, UserId, UserId>;

  expires_at: ColumnType<number, number, number>;

  two_factor_verified: ColumnType<number, number | undefined, number>;
}

export type Session = Selectable<SessionTable>;

export type NewSession = Insertable<SessionTable>;

export type SessionUpdate = Updateable<SessionTable>;
