// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { LocationId } from './Location';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.site */
export type SiteId = number & { __brand: 'public.site' };

/** Represents the Kysely type for the site table. */
export default interface SiteTable {
  id: ColumnType<SiteId, SiteId | undefined, SiteId>;

  is_active: ColumnType<boolean, boolean | undefined, boolean>;

  name: ColumnType<string, string, string>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;

  deleted_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  location_id: ColumnType<LocationId, LocationId, LocationId>;
}

export type Site = Selectable<SiteTable>;

export type NewSite = Insertable<SiteTable>;

export type SiteUpdate = Updateable<SiteTable>;
