// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UserId } from './User';
import type { SiteId } from './Site';
import type { RoleId } from './Role';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.user_site_role */
export type UserSiteRoleId = number & { __brand: 'public.user_site_role' };

/** Represents the Kysely type for the user_site_role table. */
export default interface UserSiteRoleTable {
  id: ColumnType<UserSiteRoleId, UserSiteRoleId | undefined, UserSiteRoleId>;

  user_id: ColumnType<UserId, UserId, UserId>;

  site_id: ColumnType<SiteId | null, SiteId | null, SiteId | null>;

  role_id: ColumnType<RoleId, RoleId, RoleId>;

  status: ColumnType<number, number | undefined, number>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;

  deleted_at: ColumnType<Date | null, Date | string | null, Date | string | null>;
}

export type UserSiteRole = Selectable<UserSiteRoleTable>;

export type NewUserSiteRole = Insertable<UserSiteRoleTable>;

export type UserSiteRoleUpdate = Updateable<UserSiteRoleTable>;
