// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UserId } from './User';
import type { VerificationSessionId } from './VerificationSession';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.user_module_verification */
export type UserModuleVerificationId = number & { __brand: 'public.user_module_verification' };

/** Represents the Kysely type for the user_module_verification table. */
export default interface UserModuleVerificationTable {
  id: ColumnType<UserModuleVerificationId, UserModuleVerificationId | undefined, UserModuleVerificationId>;

  user_id: ColumnType<UserId, UserId, UserId>;

  module_id: ColumnType<number, number, number>;

  verified_by_user_id: ColumnType<UserId | null, UserId | null, UserId | null>;

  verified_at: ColumnType<Date, Date | string | undefined, Date | string>;

  notes: ColumnType<string | null, string | null, string | null>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;

  evidence_file_url: ColumnType<string | null, string | null, string | null>;

  verification_session_id: ColumnType<VerificationSessionId | null, VerificationSessionId | null, VerificationSessionId | null>;

  status: ColumnType<string, string | undefined, string>;
}

export type UserModuleVerification = Selectable<UserModuleVerificationTable>;

export type NewUserModuleVerification = Insertable<UserModuleVerificationTable>;

export type UserModuleVerificationUpdate = Updateable<UserModuleVerificationTable>;
