// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UserId } from './User';
import type { LocalCategoryId } from './LocalCategory';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.user_category */
export type UserCategoryId = number & { __brand: 'public.user_category' };

/** Represents the Kysely type for the user_category table. */
export default interface UserCategoryTable {
  id: ColumnType<UserCategoryId, UserCategoryId | undefined, UserCategoryId>;

  user_id: ColumnType<UserId, UserId, UserId>;

  local_category_id: ColumnType<LocalCategoryId | null, LocalCategoryId | null, LocalCategoryId | null>;

  master_category_id: ColumnType<number | null, number | null, number | null>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type UserCategory = Selectable<UserCategoryTable>;

export type NewUserCategory = Insertable<UserCategoryTable>;

export type UserCategoryUpdate = Updateable<UserCategoryTable>;
