// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.user */
export type UserId = number & { __brand: 'public.user' };

/** Represents the Kysely type for the user table. */
export default interface UserTable {
  id: ColumnType<UserId, UserId | undefined, UserId>;

  google_id: ColumnType<string | null, string | null, string | null>;

  email: ColumnType<string, string, string>;

  first_name: ColumnType<string, string, string>;

  last_name: ColumnType<string, string, string>;

  password_hash: ColumnType<string, string, string>;

  email_verified: ColumnType<boolean, boolean | undefined, boolean>;

  totp_key: ColumnType<unknown | null, unknown | null, unknown | null>;

  recovery_code: ColumnType<unknown, unknown, unknown>;

  phone_number: ColumnType<string | null, string | null, string | null>;

  status: ColumnType<number, number | undefined, number>;

  deleted: ColumnType<boolean, boolean | undefined, boolean>;
}

export type User = Selectable<UserTable>;

export type NewUser = Insertable<UserTable>;

export type UserUpdate = Updateable<UserTable>;
