// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UserId } from './User';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.user_scorm_attempt */
export type UserScormAttemptId = number & { __brand: 'public.user_scorm_attempt' };

/** Represents the Kysely type for the user_scorm_attempt table. */
export default interface UserScormAttemptTable {
  id: ColumnType<UserScormAttemptId, UserScormAttemptId | undefined, UserScormAttemptId>;

  user_id: ColumnType<UserId, UserId, UserId>;

  module_resource_id: ColumnType<number, number, number>;

  module_id: ColumnType<number | null, number | null, number | null>;

  lesson_status: ColumnType<string | null, string | null, string | null>;

  raw_score: ColumnType<string | null, string | null, string | null>;

  max_score: ColumnType<string | null, string | null, string | null>;

  min_score: ColumnType<string | null, string | null, string | null>;

  session_time: ColumnType<string | null, string | null, string | null>;

  suspend_data: ColumnType<string | null, string | null, string | null>;

  lesson_location: ColumnType<string | null, string | null, string | null>;

  attempt_started_at: ColumnType<Date, Date | string | undefined, Date | string>;

  attempt_completed_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type UserScormAttempt = Selectable<UserScormAttemptTable>;

export type NewUserScormAttempt = Insertable<UserScormAttemptTable>;

export type UserScormAttemptUpdate = Updateable<UserScormAttemptTable>;
