// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UserId } from './User';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.user_job_role */
export type UserJobRoleId = number & { __brand: 'public.user_job_role' };

/** Represents the Kysely type for the user_job_role table. */
export default interface UserJobRoleTable {
  id: ColumnType<UserJobRoleId, UserJobRoleId | undefined, UserJobRoleId>;

  user_id: ColumnType<UserId, UserId, UserId>;

  job_role_id: ColumnType<number, number, number>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type UserJobRole = Selectable<UserJobRoleTable>;

export type NewUserJobRole = Insertable<UserJobRoleTable>;

export type UserJobRoleUpdate = Updateable<UserJobRoleTable>;
