// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UserId } from './User';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.user_module_submission */
export type UserModuleSubmissionId = number & { __brand: 'public.user_module_submission' };

/** Represents the Kysely type for the user_module_submission table. */
export default interface UserModuleSubmissionTable {
  id: ColumnType<UserModuleSubmissionId, UserModuleSubmissionId | undefined, UserModuleSubmissionId>;

  user_id: ColumnType<UserId, UserId, UserId>;

  module_id: ColumnType<number, number, number>;

  file_url: ColumnType<string, string, string>;

  status: ColumnType<string, string | undefined, string>;

  reviewer_id: ColumnType<UserId | null, UserId | null, UserId | null>;

  reviewer_feedback: ColumnType<string | null, string | null, string | null>;

  due_date: ColumnType<Date | null, Date | string | null, Date | string | null>;

  submitted_at: ColumnType<Date, Date | string | undefined, Date | string>;

  reviewed_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type UserModuleSubmission = Selectable<UserModuleSubmissionTable>;

export type NewUserModuleSubmission = Insertable<UserModuleSubmissionTable>;

export type UserModuleSubmissionUpdate = Updateable<UserModuleSubmissionTable>;
