// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UserId } from './User';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.user_course */
export type UserCourseCourseId = number & { __brand: 'public.user_course' };

/** Represents the Kysely type for the user_course table. */
export default interface UserCourseTable {
  user_id: ColumnType<UserId, UserId, UserId>;

  course_id: ColumnType<UserCourseCourseId, UserCourseCourseId, UserCourseCourseId>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type UserCourse = Selectable<UserCourseTable>;

export type NewUserCourse = Insertable<UserCourseTable>;

export type UserCourseUpdate = Updateable<UserCourseTable>;
