// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UserId } from './User';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.verification_session */
export type VerificationSessionId = number & { __brand: 'public.verification_session' };

/** Represents the Kysely type for the verification_session table. */
export default interface VerificationSessionTable {
  id: ColumnType<VerificationSessionId, VerificationSessionId | undefined, VerificationSessionId>;

  module_id: ColumnType<number, number, number>;

  verified_by_user_id: ColumnType<UserId | null, UserId | null, UserId | null>;

  verified_at: ColumnType<Date, Date | string | undefined, Date | string>;

  notes: ColumnType<string | null, string | null, string | null>;

  evidence_file_url: ColumnType<string | null, string | null, string | null>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;

  status: ColumnType<string, string | undefined, string>;
}

export type VerificationSession = Selectable<VerificationSessionTable>;

export type NewVerificationSession = Insertable<VerificationSessionTable>;

export type VerificationSessionUpdate = Updateable<VerificationSessionTable>;
